In [2]:
#confirm installation and required version
import numpy
import pandas
import matplotlib
import torch

print(numpy.__version__)
print(pandas.__version__)
print(matplotlib.__version__)
print(torch.__version__)

1.25.1
2.0.3
3.7.2
2.0.1+cpu


### Data type in Pytorch 

In [3]:
#create a scaler
scl = torch.tensor(7)
print(scl)
print(scl.ndim)
print(scl.dtype)

tensor(7)
0
torch.int64


In [4]:
#converting tensor to int
var_int=scl.item()
print(var_int)
print(type(var_int))

7
<class 'int'>


In [5]:
#creating vector
vec = torch.tensor([7,7])
print(vec)
print(vec.dtype)
print(vec.shape)
print(vec.ndim)

tensor([7, 7])
torch.int64
torch.Size([2])
1


In [6]:
# create a matrix
mat = torch.tensor([[1,2],[3,4]])
print(mat)
print(mat.shape)
print(mat.dtype)
print(len(mat))

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64
2


In [8]:
#tensor
ten = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(ten)
print(ten.shape)
print(ten.dtype)
print(len(ten))
print(ten.ndim)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
torch.int64
1
3


### Random Tensors

In [11]:
ran = torch.rand(3,4)
print(ran)
print(ran.ndim)
print(len(ran))
print(type(ran))

tensor([[0.3369, 0.7835, 0.5110, 0.5511],
        [0.2347, 0.8254, 0.2918, 0.1796],
        [0.6029, 0.0319, 0.2334, 0.6929]])
2
3
<class 'torch.Tensor'>


In [12]:
#random tensor of image size
random_image_size_tensor=torch.rand(size=(224,224,3))

print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


In [13]:
#creating tensor with zero
zero = torch.zeros(size=(3,4))
print(zero)

#creating tensors with ones
ones = torch.ones(size=(4,3))
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [19]:
#creating a tensor with range
ran = torch.arange(0,10,dtype=int)
print(ran)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [26]:
#tuple 
li = ["Rohit",50000, '1234']
print(li)

tu = ("Rohit",50000,'1234')
print(tu)




tu1 = (1,)
print(type(tu1))


['Rohit', 50000, '1234']
('Rohit', 50000, '1234')
<class 'tuple'>


In [27]:
#sets 
se={1,2,3}
se1={3}
